import { Directive, HostListener, Input } from "@angular/core";
import { AbstractControl } from "@angular/forms";

@Directive({
    selector: "[appMaxLength]"
})
export class MaxLengthDirective
{
    @Input() appMaxLength: string;

    constructor() { }

    @HostListener("keydown", ["$event"])
    onKeydown(event: KeyboardEvent)
    {
        const value = (event.target as HTMLInputElement).value;
        const maxLength = parseInt(this.appMaxLength, 10);
        const allowedKeys = [
            "Backspace",
            "Delete",
            "Tab",
            "Escape",
            "Enter",
            "ArrowLeft",
            "ArrowRight"
        ];
        if (value.length >= maxLength && !allowedKeys.includes(event.key))
        {
            event.preventDefault();
            event.stopPropagation();
        }
    }
}

@Directive({
    selector: "[appNoExponentNoDecimal]"
})
export class NoExponentNoDecimalDirective
{
    constructor() { }

    validate(control: AbstractControl): { [key: string]: any } | null
    {
        const forbiddenChars = ["e", "."];
        const value = control.value;
        if (value && forbiddenChars.some((char) => value.includes(char)))
        {
            return { forbiddenChars: true };
        }
        return null;
    }
}


let UIConfigItemsForPreEdu = [
    {
        "ExamCode": "1",
        "UIConfigItems": [
            {
                "Id": 289,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeGroup",
                "LabelName": "Group",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 290,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeRollNo",
                "LabelName": "Roll No",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 291,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeBoard",
                "LabelName": "Board",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 292,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeRegNo",
                "LabelName": "Reg No",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 293,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegePassingYear",
                "LabelName": "Passing Year",
                "KeyValue": "2017",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 294,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeInstitute",
                "LabelName": "Institute",
                "KeyValue": "XYZ Institute",
                "Visible": true,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 295,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeExamHeldIn",
                "LabelName": "Exam Held In",
                "KeyValue": "",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 296,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeGPA",
                "LabelName": "GPA",
                "KeyValue": "0.000",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 297,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeGPAwithout4thsubject",
                "LabelName": "GPA without 4th subject",
                "KeyValue": "0.000",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 298,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeExamination",
                "LabelName": "Examination",
                "KeyValue": "10021",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 299,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeSubject",
                "LabelName": "Subject",
                "KeyValue": "",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 300,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeDistrict",
                "LabelName": "District",
                "KeyValue": "1",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 301,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeFromSession",
                "LabelName": "From Session",
                "KeyValue": "0",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 302,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeToSession",
                "LabelName": "To Session",
                "KeyValue": "0",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 303,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeCourseDuration",
                "LabelName": "Course Duration",
                "KeyValue": "",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 304,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeTotalCredit",
                "LabelName": "Total Credit",
                "KeyValue": "",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 305,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeCentreCode",
                "LabelName": "Centre Code",
                "KeyValue": "001",
                "Visible": true,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 306,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeObtainedOutofno",
                "LabelName": "Out of no",
                "KeyValue": null,
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 307,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeObtainedWithout4thsubject",
                "LabelName": "Without 4th subject",
                "KeyValue": "0.00",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 308,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeObtainedWith4thsubject",
                "LabelName": "With 4th subject",
                "KeyValue": "0.00",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 309,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeObtainedResult",
                "LabelName": "Result",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            }
        ]
    },
    {
        "ExamCode": "2",
        "UIConfigItems": [
            {
                "Id": 289,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeGroup",
                "LabelName": "Group",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 290,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeRollNo",
                "LabelName": "Roll No",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 291,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeBoard",
                "LabelName": "Board",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 292,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeRegNo",
                "LabelName": "Reg No",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 293,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegePassingYear",
                "LabelName": "Passing Year",
                "KeyValue": "2020",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 294,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeInstitute",
                "LabelName": "Institute",
                "KeyValue": "XYZ Institute",
                "Visible": true,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 295,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeExamHeldIn",
                "LabelName": "Exam Held In",
                "KeyValue": "",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 296,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeGPA",
                "LabelName": "GPA",
                "KeyValue": "0.000",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 297,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeGPAwithout4thsubject",
                "LabelName": "GPA without 4th subject",
                "KeyValue": "0.000",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 298,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeExamination",
                "LabelName": "Examination",
                "KeyValue": "10022",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 299,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeSubject",
                "LabelName": "Subject",
                "KeyValue": "",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 300,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeDistrict",
                "LabelName": "District",
                "KeyValue": "1",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 301,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeFromSession",
                "LabelName": "From Session",
                "KeyValue": "0",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 302,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeToSession",
                "LabelName": "To Session",
                "KeyValue": "0",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 303,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeCourseDuration",
                "LabelName": "Course Duration",
                "KeyValue": "",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 304,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeTotalCredit",
                "LabelName": "Total Credit",
                "KeyValue": "",
                "Visible": false,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 305,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeCentreCode",
                "LabelName": "Centre Code",
                "KeyValue": "001",
                "Visible": true,
                "Required": false,
                "Message": "",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 306,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeObtainedOutofno",
                "LabelName": "Out of no",
                "KeyValue": null,
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 307,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeObtainedWithout4thsubject",
                "LabelName": "Without 4th subject",
                "KeyValue": "0.00",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 308,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeObtainedWith4thsubject",
                "LabelName": "With 4th subject",
                "KeyValue": "0.00",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            },
            {
                "Id": 309,
                "ClientId": 0,
                "KeyName": "previousAcademicInfoCollegeObtainedResult",
                "LabelName": "Result",
                "KeyValue": "",
                "Visible": true,
                "Required": true,
                "Message": "The Field is Required!",
                "FormName": "Previous Academic Information Collage",
                "ActiveStatus": true
            }
        ]
    }
]


let ssss={
    "Id": 116390,
    "CircularId": null,
    "CircularDetailId": 275,
    "CircularTitle": "test ui c 2",
    "ApplyDeclaration": "Apply now",
    "ApplicantId": null,
    "ClientId": null,
    "ClientName": null,
    "ClientAddress": null,
    "ClientPhone": null,
    "ClientLogo": null,
    "ProgramType": null,
    "StudentID": "CMMZTXOWUX",
    "StudentIDC": "",
    "UserId": 2032,
    "SourceID": 1,
    "ProgramID": 1035,
    "SubjectID": 0,
    "GroupID": 1034,
    "ClassID": 0,
    "SectionID": 0,
    "ShiftID": 1007,
    "SessionID": 1053,
    "VersionID": 1009,
    "StudentCatID": 1042,
    "IsDefense": null,
    "GenderName": null,
    "ProgramName": "Eleven",
    "ShiftName": "Morning",
    "VersionName": "Bangla",
    "GroupName": "Science",
    "CategoryName": "External",
    "SessionName": "2023-2024",
    "ClassName": "--",
    "SectionName": "--",
    "SubjectName": "--",
    "ReligionName": "Islam",
    "HomeDistrictName": "Barguna",
    "Nationality": "Bangladeshi",
    "StudentRoll": "CMMZTXOWUX",
    "StudentName": "Test cc Full Name",
    "FatherName": "Test cc Father's Name",
    "MotherName": "Test cc Mother's Name",
    "PresentAddr": "--",
    "ContactNo": "33300000001",
    "IsRegular": "Y",
    "IsActive": "Y",
    "IsPromotion": "N",
    "BrdVrstyID": 1033,
    "AdminType": "N",
    "AdmissionStatus": "ADMITTED",
    "StudentIDType": "FIXED",
    "IsArchive": "N",
    "IDCardNoS": "--",
    "HouseID": 0,
    "IDCardNoG": "--",
    "IDCardNoF": "--",
    "IDCardNoM": "--",
    "StudentNameBangla": "Full Name Bangla",
    "FatherNameBangla": "Test cc Father's Name (Bangla)",
    "MotherNameBangla": "Test cc Mother's Name Bangla",
    "TrackingID": "--",
    "TranStatus": 0,
    "BankTranId": null,
    "IsSendSMS": "N",
    "FlagStudentInfoSaved": true,
    "FlagGuardianInfoSaved": true,
    "FlagAddressInfoSaved": true,
    "FlagPreEduInfoSaved": false,
    "FlagLastEduInfoSaved": true,
    "FlagCourseInfoSaved": false,
    "StudentMasterId": null,
    "BirthDate": "2008-12-01T00:00:00",
    "BirthID": "44000000000000000",
    "StudentSex": "M",
    "BloodGroup": "A+",
    "NationalID": 10009,
    "ReligionID": 1028,
    "CurID": null,
    "EmailAddress": "d@d.com",
    "HomeDisID": 2,
    "ContactNoS": "33300000000",
    "ContactNoH": "--",
    "FirstName": "First Name",
    "MiddleName": "Middle Name",
    "LastName": "Last Name",
    "NickName": "Nick Name",
    "PhotoPathS": "https://allpicture.blob.core.windows.net/test-vortibd\\students\\116390_2023-12-28_09-30-37-145.png",
    "StudentFBID": null,
    "StudentTwiter": null,
    "AdmissionNo": null,
    "AdminDate": null,
    "FirstAdminDate": null,
    "AdminProgramID": null,
    "AdminProgram": null,
    "AdminSectionID": null,
    "AdminSection": "--",
    "AdminRoll": null,
    "AdminGroupID": null,
    "AdminGroup": "Science",
    "LastInstitute": "Last School Name",
    "TCInfo": "TC Info",
    "LastExam": "Last Exam Name",
    "LastExamResult": "Last Result",
    "BlockReason": null,
    "BlockDate": null,
    "RelationOneN": null,
    "RelationOneR": null,
    "RelationOneID": null,
    "RelationOneD": null,
    "RelationTwoN": null,
    "RelationTwoR": null,
    "RelationTwoID": null,
    "RelationTwoD": null,
    "BaptizeStatus": null,
    "BaptizeDate": null,
    "DormitoryID": null,
    "DormitoryName": null,
    "HostelID": null,
    "HostelName": null,
    "RoomNo": null,
    "BedNo": null,
    "IsFacultyHouse": null,
    "EthGroupID": null,
    "EthGroup": null,
    "DenomID": null,
    "Denom": null,
    "ContactNoF": "54560000090",
    "EmailF": "fa@f.com",
    "FatherOfficeName": "Father's Office Name",
    "FatherOfficeAddr": "Father's Office Address",
    "FatherOcpID": 1091,
    "FatherOcpName": "Private Services",
    "FatherOfficeDesig": "Father's Designation",
    "FatherOfficePhone": "7121200000000",
    "FatherTIN": "5690000000000000",
    "NationalIDF": "67000000000000000",
    "AnnualIncomeF": 1281,
    "PhotoPathF": "https://allpicture.blob.core.windows.net/test-vortibd\\father\\116390_2023-12-28_11-00-45-249.png",
    "ContactNoM": "45400000001",
    "EmailM": "f@e.com",
    "MotherOfficeName": "Mother's Office Name ",
    "MotherOfficeAddr": "Mother's Office Address ",
    "MotherOcpID": 1091,
    "MotherOcpName": "Private Services",
    "MotherOfficeDesig": "Mother's Designation",
    "MotherOfficePhone": "234345000001",
    "MotherTIN": "2424900000001",
    "NationalIDM": "3434000000001",
    "AnnualIncomeM": 1281,
    "PhotoPathM": "https://allpicture.blob.core.windows.net/test-vortibd\\mother\\116390_2023-12-28_11-00-45-440.png",
    "GuardianName": "Test cc Father's Name",
    "GuardianR": "Father",
    "ContactNoG": "54560000090",
    "EmailG": "fa@f.com",
    "GuardOfficeName": "Father's Office Name",
    "GuardOfficeAddr": "Father's Office Address",
    "GuardianOcpID": 1091,
    "GuardianOcpName": "Private Services",
    "GuardOfficeDesig": "Father's Designation",
    "GuardOfficePhone": "7121200000000",
    "GuardTIN": "5690000000000000",
    "NationalIDG": "67000000000000000",
    "AnnualIncomeG": 1280,
    "PhotoPathG": "https://allpicture.blob.core.windows.net/test-vortibd\\guardian\\116390_2023-12-28_17-50-43-729.png",
    "ArmyNo": "",
    "RegimentNo": "",
    "DefencePerson": "",
    "FatherRankID": null,
    "FatherRank": null,
    "UnitID": null,
    "UnitName": null,
    "ChildNo": 0,
    "StationName": "",
    "IsRetired": "",
    "RetireDate": null,
    "DistrictID": null,
    "MissionStartDate": "1900-01-01T00:00:00",
    "MissionEndDate": "1900-01-01T00:00:00",
    "PlaceOfMission": "",
    "CreateDate": null,
    "CreateBy": null,
    "UpdateDate": null,
    "UpdateBy": null,
    "CompNm": null,
    "PhotoUrlS": null,
    "PhotoUrlF": "",
    "PhotoUrlM": "",
    "PhotoUrlG": "",
    "SkinColor": null,
    "StudentHeight": "60",
    "StudentWeight": "70",
    "OwnHouse": "Y",
    "HouseIncome": 10000,
    "HouseExpense": 4000,
    "FatherSign": "https://allpicture.blob.core.windows.net/test-vortibd/signature",
    "MotherSign": "https://allpicture.blob.core.windows.net/test-vortibd/signature",
    "GuardinSign": "https://allpicture.blob.core.windows.net/test-vortibd/signature",
    "StudentSign": "https://allpicture.blob.core.windows.net/test-vortibd/signature",
    "OthersSkill": null,
    "Hobby": "none",
    "InterestedClub": "--",
    "IsAutism": "N",
    "FreedomFighter": "N",
    "SameInstituteOne": null,
    "SameInstituteTwo": null,
    "FatherEducation": "Father's Education",
    "MotherEducation": "Mother's Education",
    "GuardianEducation": "Father's Education",
    "BaBssSnkIdNo": "",
    "LastSchoolAdd": "Institute Address",
    "LastProgram": null,
    "LastSection": "Section",
    "LastRoll": "Roll",
    "LastTcNo": "TC No",
    "LastTcDate": "2021-12-31T18:00:00",
    "ProgramIDOne": null,
    "SectionIDOne": null,
    "RollOne": null,
    "ProgramIDTwo": null,
    "SectionIDTwo": null,
    "RollTwo": null,
    "BirthdayOne": null,
    "StudentIDOne": null,
    "BirthdayTwo": null,
    "StudentIDTwo": null,
    "VehicleStatus": null,
    "PrimaryCarNo": null,
    "PrimaryMotorCycle": null,
    "PrimaryOthers": null,
    "AlternateCarNo": null,
    "AlternateMotorCycle": null,
    "AlternateOthers": null,
    "IsOwnInstitute": null,
    "AdmissionRoll": null,
    "GurdianNameBangla": null,
    "EmployeeNoF": null,
    "DepartmentF": null,
    "EmployeeNoM": null,
    "DepartmentM": null,
    "EmployeeNoG": null,
    "DepartmentG": null,
    "AmbitionID": null,
    "HouseSRA": "Present Address House",
    "PlotSRA": "--",
    "RoadSRA": "Present Address Road",
    "BlockSRA": "Present Address Block",
    "SectionSRA": "Present Address Section",
    "SectorSRA": "Present Address Sector",
    "AreaSRA": "69",
    "WardSRA": "--",
    "WardNoSRA": "Present Address Ward No",
    "DistrictIDSRA": 101,
    "DivisionIDSRA": 3,
    "UpazilaIDSRA": 0,
    "UnionIDSRA": 0,
    "PaurashavaIDSRA": 0,
    "PostOfficeIDSRA": 0,
    "PostCodeSRA": "111",
    "PoliceStationIDSRA": 0,
    "VillageSRA": "Present Address Village",
    "AddressSRA": "Present Address Address (English) ",
    "AddressSRABangla": "",
    "DistrictSRA": "Dhaka",
    "DivisionSRA": "Dhaka",
    "UpazilaSRA": "",
    "UnionSRA": "",
    "PaurashavaSRA": "",
    "PostOfficeSRA": "",
    "PoliceStationSRA": "",
    "HouseLGA": "Present Address House",
    "PlotLGA": "Present Address Plot",
    "RoadLGA": "Present Address Road",
    "BlockLGA": "Present Address Block",
    "SectionLGA": "Present Address Section",
    "SectorLGA": "Present Address Sector",
    "AreaLGA": "69",
    "WardLGA": "--",
    "WardNoLGA": "Present Address Ward No",
    "DistrictIDLGA": 101,
    "DivisionIDLGA": 3,
    "UpazilaIDLGA": 0,
    "UnionIDLGA": 0,
    "PaurashavaIDLGA": 0,
    "PostOfficeIDLGA": 0,
    "PostCodeLGA": "111",
    "PoliceStationIDLGA": 204,
    "DistrictLGA": "Dhaka",
    "DivisionLGA": "Dhaka",
    "UpazilaLGA": "",
    "UnionLGA": "",
    "PaurashavaLGA": "",
    "PostOfficeLGA": "",
    "PoliceStationLGA": "Doulatkhan",
    "VillageLGA": "Present Address Village",
    "AddressLGA": "Present Address Address (English) ",
    "HousePA": "Present Address House",
    "PlotPA": "Present Address Plot",
    "RoadPA": "Present Address Road",
    "BlockPA": "Present Address Block",
    "SectionPA": "Present Address Section",
    "SectorPA": "Present Address Sector",
    "AreaPA": "69",
    "WardPA": "--",
    "WardNoPA": "Present Address Ward No",
    "DistrictIDPA": 101,
    "DivisionIDPA": 3,
    "UpazilaIDPA": 0,
    "UnionIDPA": 0,
    "PaurashavaIDPA": 0,
    "PostOfficeIDPA": 0,
    "DistrictPA": "Dhaka",
    "DivisionPA": "Dhaka",
    "UpazilaPA": "",
    "UnionPA": "",
    "PaurashavaPA": "",
    "PostOfficePA": "",
    "PoliceStationPA": "Doulatkhan",
    "PostCodePA": "111",
    "PoliceStationIDPA": 204,
    "VillagePA": "Present Address Village",
    "AddressPA": "Present Address Address (English) ",
    "AddressPABangla": "",
    "PreEdu": [
        {
            "SrlNo": 0,
            "ExamCode": "1",
            "ExamID": 10016,
            "ExamName": "PEC",
            "PreEduSubjectID": 0,
            "PreEduSubjectName": "--",
            "PreEduGroupID": 1033,
            "PreEduGroupName": "--",
            "PreEduBoardID": 1033,
            "PreEduBoardName": "Dhaka",
            "PreEduAreaID": 19,
            "PreEduAreaName": "Dhaka",
            "CentreCode": "100",
            "EducationIns": "PSC Information Institute",
            "TotalMarks": null,
            "Without4th": 5,
            "With4th": 5,
            "Result": "100",
            "ResultOn": "G",
            "PassYear": 2013,
            "Session1": 2013,
            "Session2": 2013,
            "RgdNo": "400001",
            "RollNo": "300001",
            "Duration": "12",
            "TotalCredit": "100",
            "ExamHeld": "2013",
            "PreEduIsRegular": "Y",
            "CasualRoll": "",
            "IssueNo": null,
            "IssueDate": "2022-12-21T12:05:22.12",
            "IssueType": "N",
            "PreEduSourceID": 1,
            "TotalMarksWithTenSub": 0,
            "TotalMarksWithoutSub": 0
        },
        {
            "SrlNo": 0,
            "ExamCode": "2",
            "ExamID": 10017,
            "ExamName": "JSC",
            "PreEduSubjectID": 0,
            "PreEduSubjectName": "--",
            "PreEduGroupID": 1033,
            "PreEduGroupName": "--",
            "PreEduBoardID": 1033,
            "PreEduBoardName": "Dhaka",
            "PreEduAreaID": 19,
            "PreEduAreaName": "Dhaka",
            "CentreCode": "100",
            "EducationIns": "JSC/JDC Information Institute",
            "TotalMarks": null,
            "Without4th": 5,
            "With4th": 5,
            "Result": "100",
            "ResultOn": "G",
            "PassYear": 2015,
            "Session1": 2015,
            "Session2": 2015,
            "RgdNo": "300201",
            "RollNo": "300001",
            "Duration": "12",
            "TotalCredit": "100",
            "ExamHeld": "2015",
            "PreEduIsRegular": "Y",
            "CasualRoll": "",
            "IssueNo": null,
            "IssueDate": "2022-12-21T12:05:22.12",
            "IssueType": "N",
            "PreEduSourceID": 1,
            "TotalMarksWithTenSub": 0,
            "TotalMarksWithoutSub": 0
        },
        {
            "SrlNo": 0,
            "ExamCode": "3",
            "ExamID": 10018,
            "ExamName": "SSC",
            "PreEduSubjectID": 0,
            "PreEduSubjectName": "--",
            "PreEduGroupID": 1034,
            "PreEduGroupName": "Science",
            "PreEduBoardID": 1033,
            "PreEduBoardName": "Dhaka",
            "PreEduAreaID": 19,
            "PreEduAreaName": "Dhaka",
            "CentreCode": "2017",
            "EducationIns": "SSC/ Dakhil Information Institute",
            "TotalMarks": null,
            "Without4th": 5,
            "With4th": 5,
            "Result": "2017",
            "ResultOn": "G",
            "PassYear": 2018,
            "Session1": 2017,
            "Session2": 2017,
            "RgdNo": "30202",
            "RollNo": "30002",
            "Duration": "24",
            "TotalCredit": "2017",
            "ExamHeld": "2018",
            "PreEduIsRegular": "Y",
            "CasualRoll": "",
            "IssueNo": null,
            "IssueDate": "2022-12-21T12:05:22.12",
            "IssueType": "N",
            "PreEduSourceID": 1,
            "TotalMarksWithTenSub": 0,
            "TotalMarksWithoutSub": 0
        }
    ],
    "ThirdSubjectCourseId": 0,
    "FourthSubjectCourseId": 0,
    "CompSubject1CourseId": 0,
    "CompSubject2CourseId": 0,
    "ThirdSubjectCourse": "",
    "FourthSubjectCourse": ""
}


